### ISSUE TITLE
Connection to server got closed. Server will not be restarted

### ISSUE THREAD

**Issue by mrGibi** [jack-karamanian/vscode-perlsyntax#4]
Hi,

While opening [this](https://st.aticpan.org/source/MOB/Forks-Super-0.93/lib/Forks/Super.pm) file with VSCode, Im getting this:
```
Error: No diagnostics were produced on perl exit: write EPIPE
    at Socket.process.stdin.on (/Users/gibi/.vscode/extensions/jackkaramanian.perl-syntax-0.0.6/server/PerlLinter.js:24:23)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at onwriteError (_stream_writable.js:341:10)
    at onwrite (_stream_writable.js:359:5)
    at fireErrorCallbacks (net.js:480:13)
    at Socket._destroy (net.js:521:3)
    at WriteWrap.afterWrite [as oncomplete] (net.js:815:10)
[Error - 22:16:08] Connection to server got closed. Server will not be restarted.
```

Is it just me? ;)

**Comment by mrGibi** [comment]
So I guess its only me... ;)

**Comment by jonasbn** [comment]
@mrGibi I observe this too. I am trying to find some time to do some more investigation into root cause.
